### PR TITLE
Bugs in SampledJointEntropy fixed

### PR DESCRIPTION
**Pull request by Aktsvigun**
Hi,
I saw two mismatches between `ExactJointEntropy` and `SampledJointEntropy`, although to my knowledge, the logic of their computations should coincide.

- First, the method `compute` in `SampledJointEntropy` returns the **mean** of the _logarithms of probas_ instead of the  **sum** of the _product of the probas and their logarithms_ (taking **mean** / **sum** is not really important since we are aware of the sampled size, still it preserves the cardinality). 
- Second, matmul in the method `compute_batch` deals with `log_probs_B_K_C`, however, `self.sampled_joint_probs_M_K` are not logarithms - consequently, we should take the exp of `log_probs_B_K_C`. 

This PR aims at fixing these bugs.

### CODE REVIEW

**Comment by Aktsvigun** [comment]
I am also unsure of the lines 236-238 - could you please explain, what is their purpose?

**Comment by BlackHC** [comment]
Thanks for submitting this. These are not bugs.

Re 2.
```
--                    chunked_log_probs_b_K_C[i].to(self.sampled_joint_probs_M_K, non_blocking=True).exp(),
++                    chunked_probs_b_K_C[i].to(self.sampled_joint_probs_M_K, non_blocking=True).exp(),
```
Note the .exp() at the end. Your changes would turn it into an .exp().exp() essentially.

Re 1.

```
          sampled_joint_probs_M = torch.mean(self.sampled_joint_probs_M_K, dim=1, keepdim=False)
--        nats_M = -torch.log(sampled_joint_probs_M)
--        entropy = torch.mean(nats_M)
++        nats_M = -torch.log(sampled_joint_probs_M) * sampled_joint_probs_M
++        entropy = torch.sum(nats_M)
```

This change is also incorrect. An entropy is just an expectation over -log p(x): E_p(x) [ -log p(x) ]. The sampled_joint_probs_M are sampled using p(sampled_joint_probs_M) effectively. The original code computes a Monte-Carlo estimate of the expectation, ie. average over the sampled -log p(x).

The suggested change would only work if the samples in sampled_joint_probs_M were sampled uniformly.

Re lines 236-238:

This is an importance sampling term. Best to check the appendix of the paper for the details of that.

Closing this as such.

Thanks,
 Andreas

**Comment by Aktsvigun** [comment]
@BlackHC , thank you for your answer! Still, I cannot understand one major point: the result of `ExactJointEntropy.compute` and `SampledJointEntropy.compute` should coincide when C ** N < m, doesn't it? Because in this case, `SampledJointEntropy` is just the same as `ExactJointEntropy.` However, the results are very different (the attached image).

Снимок экрана 2022-02-21 в 16 14 18

**Comment by BlackHC** [comment]
You want to use the `@staticmethod` `empty` constructors: the dataclass ones simply assign directly to the underlying fields which are semantically different. Passing your `data` thus means different things in either class:

In `ExactJointEntropy`, you assign to the ` joint_probs_M_K` fields, but in `SampledJointEntropy` you assign to the `sampled_joint_probs_M_K` field. The two are not the same.

Try your code by using `ExactJointEntropy.empty(...)` first on each and then add your "data" via `add_variables` before calling `.compute()`.

The `JointEntropy` interface defines the abstractions that are valid.

Thanks,
 Andreas

**Comment by Aktsvigun** [comment]
Thanks a lot!

**Pull request closed without merging**
